package main;
class NPCGroup_AdeptusMinistorum extends NPCGroup {

	NPCGroup_AdeptusMinistorum() {
		super("Adeptus Ministorum");
	}

	@Override
	protected void setNPCList() {
		NPC npc;
		
		npc = new NPC("Novice", "30,30,30,30,30,30,30,30,35");
		npc.specialRuleList.add(Talent.knowledgable.withParameter("Imperial Creed"));
		npc.specialRuleList.add(Talent.language.withParameter("Low Gothic"));
		npc.equippedItemList.add(Clothing.ministorumRobes);
		npc.inventoryList.add(MiscItem.gelt);
		npcList.add(npc);
		
		npc = new NPC("Initiate", "30,30,30,30,30,30,30,30,35");
		npc.specialRuleList.add(Talent.knowledgable.withParameter("Adeptus Ministorum + Imperial Creed"));
		npc.specialRuleList.add(Talent.language.withParameter("Low Gothic"));
		npc.specialRuleList.add(Talent.trade_copyist);
		npc.equippedItemList.add(Clothing.ministorumRobes);
		npc.inventoryList.add(MiscItem.gelt);
		npcList.add(npc);
		
		npc = new NPC("Priest", "30,30,30,30,30,30,30,30,40");
		npc.specialRuleList.add(Talent.knowledgable.withParameter("Adeptus Ministorum + Imperial Creed"));
		npc.specialRuleList.add(Talent.language.withParameter("High Gothic + Low Gothic"));
		npc.specialRuleList.add(Talent.trade_copyist);
		npc.skillList.add(Skill.inquire.withBonus(10));
		npc.skillList.add(Skill.inspire.withBonus(10));
		npc.equippedItemList.add(Clothing.ministorumRobes);
		npc.inventoryList.add(Tool.scroll_imperialCreed);
		npc.inventoryList.add(new Item("Aquila Necklace", 0));
		npc.inventoryList.add(MiscItem.gelt);
		npcList.add(npc);
		
		npc = new NPC("Preacher", "30,30,30,30,30,30,30,30,40");
		npc.specialRuleList.add(Talent.experienced.withParameter("Imperial Creed"));
		npc.specialRuleList.add(Talent.knowledgable.withParameter("Adeptus Ministorum"));
		npc.specialRuleList.add(Talent.language.withParameter("High Gothic + Low Gothic"));
		npc.specialRuleList.add(Talent.publicSpeaker);
		npc.specialRuleList.add(Talent.trade_copyist);
		npc.specialRuleList.add(Talent.trade_loremancer);
		npc.skillList.add(Skill.inquire.withBonus(10));
		npc.skillList.add(Skill.inspire.withBonus(10));
		npc.equippedItemList.add(Clothing.ministorumRobes);
		npc.inventoryList.add(Tool.scroll_imperialCreed);
		npc.inventoryList.add(new Item("Aquila Necklace", 0));
		npc.inventoryList.add(MiscItem.gelt);
		npcList.add(npc);
		
		npc = new NPC("Cleric", "35,35,35,35,35,35,35,35,40");
		npc.specialRuleList.add(Talent.experienced.withParameter("Imperial Creed"));
		npc.specialRuleList.add(Talent.knowledgable.withParameter("Adeptus Ministorum"));
		npc.specialRuleList.add(Talent.language.withParameter("High Gothic + Low Gothic"));
		npc.specialRuleList.add(Talent.publicSpeaker);
		npc.specialRuleList.add(Talent.trade_copyist);
		npc.specialRuleList.add(Talent.trade_loremancer);
		npc.skillList.add(Skill.charm.withBonus(10));
		npc.skillList.add(Skill.command.withBonus(10));
		npc.skillList.add(Skill.inquire.withBonus(10));
		npc.skillList.add(Skill.inspire.withBonus(10));
		npc.skillList.add(Skill.persuade.withBonus(10));
		npc.skillList.add(Skill.referenceCommonLore.withBonus(10));
		npc.skillList.add(Skill.treatWounds.withBonus(0));
		npc.equippedItemList.add(Clothing.ministorumRobes);
		npc.equippedItemList.add(Armour.chainCoat);
		npc.inventoryList.add(MeleeWeapon.warHammer);
		npc.inventoryList.add(MeleeWeapon.shortsword);
		npc.inventoryList.add(RangedWeapon.pistol);
		npc.inventoryList.add(Ammo.pistol_mag);
		npc.inventoryList.add(Tool.tome_imperialCreed);
		npc.inventoryList.add(new Item("Aquila Necklace", 0));
		npc.inventoryList.add(MiscItem.gelt);
		npcList.add(npc);
		
		npc = new NPC("Confessor", "35,35,35,35,35,35,40,35,40");
		npc.specialRuleList.add(Talent.experienced.withParameter("Imperial Creed"));
		npc.specialRuleList.add(Talent.knowledgable.withParameter("Adeptus Ministorum"));
		npc.specialRuleList.add(Talent.language.withParameter("High Gothic + Low Gothic"));
		npc.specialRuleList.add(Talent.publicSpeaker);
		npc.specialRuleList.add(Talent.trade_copyist);
		npc.specialRuleList.add(Talent.trade_loremancer);
		npc.skillList.add(Skill.charm.withBonus(10));
		npc.skillList.add(Skill.command.withBonus(10));
		npc.skillList.add(Skill.inquire.withBonus(20));
		npc.skillList.add(Skill.inspire.withBonus(10));
		npc.skillList.add(Skill.persuade.withBonus(10));
		npc.skillList.add(Skill.readPerson.withBonus(20));
		npc.skillList.add(Skill.referenceCommonLore.withBonus(10));
		npc.skillList.add(Skill.treatWounds.withBonus(0));
		npc.equippedItemList.add(Clothing.ministorumRobes);
		npc.inventoryList.add(MeleeWeapon.warHammer);
		npc.inventoryList.add(MeleeWeapon.shortsword);
		npc.inventoryList.add(Tool.tome_imperialCreed);
		npc.inventoryList.add(new Item("Aquila Necklace", 0));
		npc.inventoryList.add(MiscItem.gelt);
		npcList.add(npc);
		
		npc = new NPC("Exorcist", "40,40,35,35,35,35,35,40,40");
		npc.specialRuleList.add(Talent.experienced.withParameter("Imperial Creed"));
		npc.specialRuleList.add(Talent.knowledgable.withParameter("Adeptus Ministorum"));
		npc.specialRuleList.add(Talent.language.withParameter("High Gothic + Low Gothic"));
		npc.specialRuleList.add(Talent.publicSpeaker);
		npc.specialRuleList.add(Talent.trade_copyist);
		npc.specialRuleList.add(Talent.trade_loremancer);
		npc.skillList.add(Skill.charm.withBonus(10));
		npc.skillList.add(Skill.command.withBonus(10));
		npc.skillList.add(Skill.inquire.withBonus(10));
		npc.skillList.add(Skill.inspire.withBonus(10));
		npc.skillList.add(Skill.interrogate.withBonus(20));
		npc.skillList.add(Skill.persuade.withBonus(10));
		npc.skillList.add(Skill.readPerson.withBonus(10));
		npc.skillList.add(Skill.referenceCommonLore.withBonus(10));
		npc.skillList.add(Skill.treatWounds.withBonus(0));
		npc.equippedItemList.add(Clothing.ministorumRobes);
		npc.equippedItemList.add(Armour.chainCoat);
		npc.inventoryList.add(MeleeWeapon.warHammer);
		npc.inventoryList.add(MeleeWeapon.shortsword);
		npc.inventoryList.add(RangedWeapon.pistol);
		npc.inventoryList.add(Ammo.pistol_mag);
		npc.inventoryList.add(Tool.tome_imperialCreed);
		npc.inventoryList.add(Tool.smallRelic);
		npc.inventoryList.add(new Item("Aquila Necklace", 0));
		npc.inventoryList.add(MiscItem.gelt);
		npcList.add(npc);
		
		npc = new NPC("Bishop", "35,35,35,35,35,35,40,35,45");
		npc.specialRuleList.add(Talent.educated.withParameter("Occult + Theology"));
		npc.specialRuleList.add(Talent.experienced.withParameter("Imperial Creed"));
		npc.specialRuleList.add(Talent.knowledgable.withParameter("Adeptus Ministorum"));
		npc.specialRuleList.add(Talent.language.withParameter("High Gothic + Low Gothic"));
		npc.specialRuleList.add(Talent.publicSpeaker);
		npc.specialRuleList.add(Talent.trade_copyist);
		npc.specialRuleList.add(Talent.trade_loremancer);
		npc.skillList.add(Skill.charm.withBonus(10));
		npc.skillList.add(Skill.command.withBonus(10));
		npc.skillList.add(Skill.inquire.withBonus(20));
		npc.skillList.add(Skill.inspire.withBonus(20));
		npc.skillList.add(Skill.persuade.withBonus(10));
		npc.skillList.add(Skill.readPerson.withBonus(20));
		npc.skillList.add(Skill.referenceCommonLore.withBonus(20));
		npc.skillList.add(Skill.referenceScholasticLore.withBonus(20));
		npc.skillList.add(Skill.treatWounds.withBonus(0));
		npc.equippedItemList.add(Clothing.ministorumRobes);
		npc.inventoryList.add(MeleeWeapon.warHammer);
		npc.inventoryList.add(MeleeWeapon.shortsword);
		npc.inventoryList.add(Tool.tome_imperialCreed);
		npc.inventoryList.add(new Item("Aquila Necklace", 0));
		npc.inventoryList.add(MiscItem.gelt);
		npcList.add(npc);
		
		npc = new NPC("Zealot", "40,40,40,40,40,35,40,40,40");
		npc.specialRuleList.add(Talent.experienced.withParameter("Imperial Creed"));
		npc.specialRuleList.add(Talent.knowledgable.withParameter("Adeptus Ministorum"));
		npc.specialRuleList.add(Talent.language.withParameter("High Gothic + Low Gothic"));
		npc.specialRuleList.add(Talent.nervesOfSteel);
		npc.specialRuleList.add(Talent.publicSpeaker);
		npc.specialRuleList.add(Talent.trade_copyist);
		npc.specialRuleList.add(Talent.trade_loremancer);
		npc.skillList.add(Skill.charm.withBonus(10));
		npc.skillList.add(Skill.command.withBonus(10));
		npc.skillList.add(Skill.inquire.withBonus(10));
		npc.skillList.add(Skill.inspire.withBonus(10));
		npc.skillList.add(Skill.interrogate.withBonus(20));
		npc.skillList.add(Skill.persuade.withBonus(10));
		npc.skillList.add(Skill.readPerson.withBonus(10));
		npc.skillList.add(Skill.referenceCommonLore.withBonus(10));
		npc.skillList.add(Skill.treatWounds.withBonus(10));
		npc.equippedItemList.add(Clothing.ministorumRobes);
		npc.equippedItemList.add(Armour.flakCoat);
		npc.inventoryList.add(MeleeWeapon.warHammer);
		npc.inventoryList.add(MeleeWeapon.shortsword);
		npc.inventoryList.add(RangedWeapon.handFlamer);
		npc.inventoryList.add(Ammo.handFlamer_canister);
		npc.inventoryList.add(RangedWeapon.pistol);
		npc.inventoryList.add(Ammo.pistol_mag);
		npc.inventoryList.add(Tool.smallishRelic);
		npc.inventoryList.add(new Item("Aquila Necklace", 0));
		npc.inventoryList.add(MiscItem.gelt);
		npcList.add(npc);
		
		npc = new NPC("Heirophant", "35,35,35,35,35,40,40,35,45");
		npc.specialRuleList.add(Talent.commanding);
		npc.specialRuleList.add(Talent.educated.withParameter("Heraldry + Occult + Philosophy"));
		npc.specialRuleList.add(Talent.experienced.withParameter("Imperial Creed"));
		npc.specialRuleList.add(Talent.specialist.withParameter("Theology"));
		npc.specialRuleList.add(Talent.haloOfCommand);
		npc.specialRuleList.add(Talent.inspiring);
		npc.specialRuleList.add(Talent.knowledgable.withParameter("Adeptus Ministorum"));
		npc.specialRuleList.add(Talent.language.withParameter("High Gothic + Low Gothic"));
		npc.specialRuleList.add(Talent.publicSpeaker);
		npc.specialRuleList.add(Talent.trade_copyist);
		npc.specialRuleList.add(Talent.trade_loremancer);
		npc.skillList.add(Skill.charm.withBonus(10));
		npc.skillList.add(Skill.command.withBonus(20));
		npc.skillList.add(Skill.inquire.withBonus(20));
		npc.skillList.add(Skill.inspire.withBonus(30));
		npc.skillList.add(Skill.persuade.withBonus(20));
		npc.skillList.add(Skill.readPerson.withBonus(20));
		npc.skillList.add(Skill.referenceCommonLore.withBonus(30));
		npc.skillList.add(Skill.referenceScholasticLore.withBonus(20));
		npc.skillList.add(Skill.treatWounds.withBonus(0));
		npc.equippedItemList.add(Clothing.ministorumRobes);
		npc.inventoryList.add(MeleeWeapon.warHammer);
		npc.inventoryList.add(MeleeWeapon.shortsword);
		npc.inventoryList.add(Tool.tome_imperialCreed);
		npc.inventoryList.add(new Item("Aquila Necklace", 0));
		npc.inventoryList.add(MiscItem.gelt);
		npcList.add(npc);
		
		npc = new NPC("Redemptionist", "50,50,40,40,40,35,40,40,40");
		npc.specialRuleList.add(Talent.adamantiumWill);
		npc.specialRuleList.add(Talent.experienced.withParameter("Imperial Creed"));
		npc.specialRuleList.add(Talent.knowledgable.withParameter("Adeptus Ministorum"));
		npc.specialRuleList.add(Talent.language.withParameter("High Gothic + Low Gothic"));
		npc.specialRuleList.add(Talent.publicSpeaker);
		npc.specialRuleList.add(Talent.trade_copyist);
		npc.specialRuleList.add(Talent.trade_loremancer);
		npc.skillList.add(Skill.charm.withBonus(10));
		npc.skillList.add(Skill.command.withBonus(10));
		npc.skillList.add(Skill.inquire.withBonus(10));
		npc.skillList.add(Skill.inspire.withBonus(10));
		npc.skillList.add(Skill.interrogate.withBonus(20));
		npc.skillList.add(Skill.persuade.withBonus(10));
		npc.skillList.add(Skill.readPerson.withBonus(10));
		npc.skillList.add(Skill.referenceCommonLore.withBonus(10));
		npc.skillList.add(Skill.treatWounds.withBonus(10));
		npc.equippedItemList.add(Clothing.ministorumRobes);
		npc.equippedItemList.add(Armour.carapaceArmour);
		npc.inventoryList.add(MeleeWeapon.warHammer);
		npc.inventoryList.add(MeleeWeapon.shortsword);
		npc.inventoryList.add(RangedWeapon.flamer);
		npc.inventoryList.add(Ammo.flamer_canister);
		npc.inventoryList.add(RangedWeapon.pistol);
		npc.inventoryList.add(Ammo.pistol_mag);
		npc.inventoryList.add(Tool.smallishRelic);
		npc.inventoryList.add(new Item("Aquila Necklace", 0));
		npc.inventoryList.add(MiscItem.gelt);
		npcList.add(npc);
		
	}
}