package main;

class NPCGroup_AdeptusMechanicus extends NPCGroup {
	
	// Ranked Characters //
	public static final NPC technographer = new NPC("Technographer",
	        "30,30,30,30,30,30,30,30,30")
			.withSpecialRule(Talent.knowledgable.withParameter("Tech"))
			.withSpecialRule(Talent.language.withParameter("Low Gothic"))
			.withSpecialRule(Talent.trade.withParameter("Armourer/Mason/Shipwright/Technomat/Wright"))
			.withSpecialRule(Bionic.mechanicusImplants)
			.withItemEquipped(Clothing.mechanicusRobes)
			.withItemInInventory(Tool.auspex)
			.withItemInInventory(Tool.combiTool)
			.withItemInInventory(MiscItem.gelt);
			
	public static final NPC mechWright = new NPC("Mech-Wright",
	        "30,30,30,30,30,30,30,30,30")
			.withSpecialRule(Talent.knowledgable.withParameter("Tech"))
			.withSpecialRule(Talent.language.withParameter("Low Gothic"))
			.withSpecialRule(Talent.trade.withParameter("Armourer/Mason/Shipwright/Technomat/Wright"))
			.withSpecialRule(Bionic.mechanicusImplants)
			.withSkill(Skill.useTech.withBonus(0))
			.withItemEquipped(Clothing.mechanicusRobes)
			.withItemInInventory(Tool.auspex)
			.withItemInInventory(Tool.combiTool)
			.withItemInInventory(MiscItem.gelt);
			
	public static final NPC electroPriest = new NPC("Electro-Priest",
	        "30,30,30,30,30,35,30,30,30")
			.withSpecialRule(Talent.knowledgable.withParameter("Tech"))
			.withSpecialRule(Talent.language.withParameter("Binary + Low Gothic"))
			.withSpecialRule(Talent.trade.withParameter("Armourer/Mason/Shipwright/Technomat/Wright"))
			.withSpecialRule(Bionic.interfacePort)
			.withSpecialRule(Bionic.luminenCapacitor)
			.withSpecialRule(Bionic.mechanicusImplants)
			.withSkill(Skill.hack.withBonus(0))
			.withSkill(Skill.useTech.withBonus(0))
			.withItemEquipped(Clothing.mechanicusRobes)
			.withItemInInventory(Tool.auspex)
			.withItemInInventory(Tool.combiTool)
			.withItemInInventory(MiscItem.gelt);
			
	public static final NPC engineSeer = new NPC("Engine-Seer",
	        "30,30,30,30,30,35,30,30,30")
			.withSpecialRule(Talent.knowledgable.withParameter("Tech"))
			.withSpecialRule(Talent.language.withParameter("Binary + Low Gothic"))
			.withSpecialRule(Talent.operate_int.withParameter("1 Vehicle Type"))
			.withSpecialRule(Talent.trade.withParameter("Armourer/Mason/Shipwright/Technomat/Wright"))
			.withSpecialRule(Bionic.augurArray)
			.withSpecialRule(Bionic.interfacePort)
			.withSpecialRule(Bionic.luminenCapacitor)
			.withSpecialRule(Bionic.mechanicusImplants)
			.withSpecialRule(Bionic.mindImpulseUnit)
			.withSkill(Skill.craft.withBonus(10))
			.withSkill(Skill.hack.withBonus(0))
			.withSkill(Skill.repair.withBonus(10))
			.withSkill(Skill.useTech.withBonus(20))
			.withItemEquipped(Clothing.mechanicusRobes)
			.withItemInInventory(Tool.combiTool)
			.withItemInInventory(MiscItem.gelt);
			
	public static final NPC techPriest_chirurgeon = new NPC("Tech-Priest (Chirurgeon)",
	        "30,30,30,30,30,40,35,30,30")
			.withSpecialRule(Talent.experienced.withParameter("Tech"))
			.withSpecialRule(Talent.language.withParameter("Binary + Low Gothic"))
			.withSpecialRule(Talent.operate_int.withParameter("1 Vehicle Type"))
			.withSpecialRule(Talent.trade.withParameter("Armourer/Mason/Shipwright/Technomat/Wright"))
			.withSpecialRule(Bionic.augurArray)
			.withSpecialRule(Bionic.interfacePort)
			.withSpecialRule(Bionic.internalReservoir)
			.withSpecialRule(Bionic.luminenCapacitor)
			.withSpecialRule(Bionic.mechanicusImplants)
			.withSpecialRule(Bionic.mechadendrite_medicae)
			.withSpecialRule(Bionic.mechadendrite_optical)
			.withSpecialRule(Bionic.vocalImplant)
			.withSkill(Skill.administerDrug.withBonus(10))
			.withSkill(Skill.craft.withBonus(10))
			.withSkill(Skill.hack.withBonus(0))
			.withSkill(Skill.inspect.withBonus(10))
			.withSkill(Skill.performSurgery.withBonus(20))
			.withSkill(Skill.repair.withBonus(10))
			.withSkill(Skill.treatWounds.withBonus(20))
			.withSkill(Skill.useTech.withBonus(20))
			.withItemEquipped(Clothing.mechanicusRobes)
			.withItemEquipped(MeleeWeapon.staff)
			.withItemInInventory(Consumable.qualityMedkit)
			.withItemInInventory(Tool.surgicalTools)
			.withItemInInventory(MiscItem.glowGlobe)
			.withItemInInventory(MiscItem.gelt);
			
	public static final NPC techPriest_militant = new NPC("Tech-Priest (Militant)",
	        "30,45,30,30,30,35,30,30,30")
			.withSpecialRule(Talent.gunslinger)
			.withSpecialRule(Talent.knowledgable.withParameter("Tech"))
			.withSpecialRule(Talent.language.withParameter("Binary + Low Gothic"))
			.withSpecialRule(Talent.luminenShock)
			.withSpecialRule(Talent.masterGunslinger)
			.withSpecialRule(Talent.operate_int.withParameter("1 Vehicle Type"))
			.withSpecialRule(Talent.trade.withParameter("Armourer"))
			.withSpecialRule(Bionic.augurArray)
			.withSpecialRule(Bionic.interfacePort)
			.withSpecialRule(Bionic.internalReservoir)
			.withSpecialRule(Bionic.luminenCapacitor)
			.withSpecialRule(Bionic.mechanicusImplants)
			.withSpecialRule(Bionic.mechadendrite_ballistic)
			.withSpecialRule(Bionic.mechadendrite_ballistic)
			.withSpecialRule(Bionic.mindImpulseUnit)
			.withSpecialRule(Bionic.vocalImplant)
			.withSkill(Skill.craft.withBonus(10))
			.withSkill(Skill.hack.withBonus(0))
			.withSkill(Skill.repair.withBonus(10))
			.withSkill(Skill.useTech.withBonus(20))
			.withItemEquipped(Clothing.mechanicusRobes)
			.withItemEquipped(MeleeWeapon.staff)
			.withItemInInventory(RangedWeapon.laspistol)
			.withItemInInventory(Ammo.laspistol_powerPack.times(2))
			.withItemInInventory(Tool.auspex)
			.withItemInInventory(MiscItem.glowGlobe)
			.withItemInInventory(MiscItem.gelt);
			
	public static final NPC techPriest = new NPC("Tech-Priest",
	        "30,30,30,35,30,40,35,30,30")
			.withSpecialRule(Talent.experienced.withParameter("Tech"))
			.withSpecialRule(Talent.language.withParameter("Binary + Low Gothic"))
			.withSpecialRule(Talent.operate_int.withParameter("1 Vehicle Type"))
			.withSpecialRule(Talent.trade.withParameter("Armourer/Mason/Shipwright/Technomat/Wright"))
			.withSpecialRule(Bionic.augurArray)
			.withSpecialRule(Bionic.ferricLure)
			.withSpecialRule(Bionic.interfacePort)
			.withSpecialRule(Bionic.internalReservoir)
			.withSpecialRule(Bionic.luminenCapacitor)
			.withSpecialRule(Bionic.mechanicusImplants)
			.withSpecialRule(Bionic.mechadendrite_manipulator)
			.withSpecialRule(Bionic.mechadendrite_utility)
			.withSpecialRule(Bionic.mindImpulseUnit)
			.withSpecialRule(Bionic.vocalImplant)
			.withSkill(Skill.craft.withBonus(20))
			.withSkill(Skill.hack.withBonus(20))
			.withSkill(Skill.inspect.withBonus(20))
			.withSkill(Skill.referenceLore.withBonus(10))
			.withSkill(Skill.repair.withBonus(20))
			.withSkill(Skill.useTech.withBonus(20))
			.withItemEquipped(Clothing.mechanicusRobes)
			.withItemEquipped(MeleeWeapon.staff)
			.withItemInInventory(Tool.combiTool)
			.withItemInInventory(MiscItem.glowGlobe)
			.withItemInInventory(Tool.lascutter)
			.withItemInInventory(MiscItem.gelt);
			
	public static final NPC technomancer = new NPC("Technomancer",
	        "30,30,30,40,30,45,35,30,30")
			.withSpecialRule(Talent.experienced.withParameter("Tech"))
			.withSpecialRule(Talent.language.withParameter("Binary + Low Gothic"))
			.withSpecialRule(Talent.operate_int.withParameter("1 Vehicle Type"))
			.withSpecialRule(Talent.trade.withParameter("Armourer/Mason/Shipwright/Technomat/Wright"))
			.withSpecialRule(Bionic.augurArray)
			.withSpecialRule(Bionic.bionicEye_pair)
			.withSpecialRule(Bionic.ferricLure)
			.withSpecialRule(Bionic.interfacePort)
			.withSpecialRule(Bionic.internalReservoir)
			.withSpecialRule(Bionic.luminenCapacitor)
			.withSpecialRule(Bionic.mechanicusImplants)
			.withSpecialRule(Bionic.mechadendrite_manipulator)
			.withSpecialRule(Bionic.mechadendrite_optical)
			.withSpecialRule(Bionic.mechadendrite_utility)
			.withSpecialRule(Bionic.mindImpulseUnit)
			.withSpecialRule(Bionic.vocalImplant)
			.withSkill(Skill.craft.withBonus(20))
			.withSkill(Skill.hack.withBonus(20))
			.withSkill(Skill.inspect.withBonus(20))
			.withSkill(Skill.interrogate.withBonus(10))
			.withSkill(Skill.referenceLore.withBonus(20))
			.withSkill(Skill.repair.withBonus(20))
			.withSkill(Skill.useTech.withBonus(20))
			.withItemEquipped(Clothing.mechanicusRobes)
			.withItemEquipped(MeleeWeapon.staff)
			.withItemInInventory(Tool.combiTool)
			.withItemInInventory(Tool.dataSlate)
			.withItemInInventory(MiscItem.glowGlobe)
			.withItemInInventory(Tool.lascutter)
			.withItemInInventory(MiscItem.gelt);
			
	public static final NPC mechDeacon = new NPC("Mech-Deacon",
	        "35,35,30,35,30,40,35,30,30")
			.withSpecialRule(Talent.experienced.withParameter("Tech"))
			.withSpecialRule(Talent.language.withParameter("Binary + Low Gothic"))
			.withSpecialRule(Talent.operate_int.withParameter("1 Vehicle Type"))
			.withSpecialRule(Talent.trade.withParameter("Armourer/Mason/Shipwright/Technomat/Wright"))
			.withSpecialRule(Bionic.augurArray)
			.withSpecialRule(Bionic.bionicEye_pair)
			.withSpecialRule(Bionic.ferricLure)
			.withSpecialRule(Bionic.interfacePort)
			.withSpecialRule(Bionic.internalReservoir)
			.withSpecialRule(Bionic.luminenCapacitor)
			.withSpecialRule(Bionic.mechanicusImplants)
			.withSpecialRule(Bionic.mechadendrite_ballistic)
			.withSpecialRule(Bionic.mechadendrite_manipulator)
			.withSpecialRule(Bionic.mechadendrite_utility)
			.withSpecialRule(Bionic.mindImpulseUnit)
			.withSpecialRule(Bionic.vocalImplant)
			.withSkill(Skill.craft.withBonus(20))
			.withSkill(Skill.hack.withBonus(20))
			.withSkill(Skill.inquire.withBonus(10))
			.withSkill(Skill.inspect.withBonus(20))
			.withSkill(Skill.interrogate.withBonus(10))
			.withSkill(Skill.navigate.withBonus(10))
			.withSkill(Skill.referenceLore.withBonus(20))
			.withSkill(Skill.repair.withBonus(30))
			.withSkill(Skill.search.withBonus(10))
			.withSkill(Skill.useTech.withBonus(30))
			.withItemEquipped(Clothing.mechanicusRobes)
			.withItemEquipped(Armour.meshVest)
			.withItemEquipped(MeleeWeapon.staff)
			.withItemInInventory(RangedWeapon.plasmaPistol)
			.withItemInInventory(Ammo.plasmaPistol_canister)
			.withItemInInventory(Tool.combiTool)
			.withItemInInventory(MiscItem.glowGlobe)
			.withItemInInventory(Tool.lascutter)
			.withItemInInventory(MiscItem.gelt);
			
	public static final NPC cyberSeer = new NPC("Cyber-Seer",
	        "30,30,30,40,30,45,35,30,30")
			.withInsanity(2)
			.withSpecialRule(Talent.experienced.withParameter("Tech"))
			.withSpecialRule(Talent.language.withParameter("Binary + Low Gothic"))
			.withSpecialRule(Talent.operate_int.withParameter("1 Vehicle Type"))
			.withSpecialRule(Talent.trade.withParameter("Armourer/Mason/Shipwright/Technomat/Wright"))
			.withSpecialRule(Talent.unveiledSecrets.withParameter("Archeotech"))
			.withSpecialRule(Bionic.augurArray)
			.withSpecialRule(Bionic.bionicEye_pair)
			.withSpecialRule(Bionic.bionicHearing)
			.withSpecialRule(Bionic.bionicLungs)
			.withSpecialRule(Bionic.cogitatorImplant)
			.withSpecialRule(Bionic.ferricLure)
			.withSpecialRule(Bionic.interfacePort)
			.withSpecialRule(Bionic.internalReservoir)
			.withSpecialRule(Bionic.luminenCapacitor)
			.withSpecialRule(Bionic.mechanicusImplants)
			.withSpecialRule(Bionic.mechadendrite_manipulator)
			.withSpecialRule(Bionic.mechadendrite_optical)
			.withSpecialRule(Bionic.mechadendrite_utility)
			.withSpecialRule(Bionic.mindImpulseUnit_goodQuality)
			.withSpecialRule(Bionic.vocalImplant)
			.withSkill(Skill.craft.withBonus(20))
			.withSkill(Skill.hack.withBonus(20))
			.withSkill(Skill.inquire.withBonus(20))
			.withSkill(Skill.inspect.withBonus(20))
			.withSkill(Skill.interrogate.withBonus(20))
			.withSkill(Skill.referenceLore.withBonus(30))
			.withSkill(Skill.repair.withBonus(20))
			.withSkill(Skill.useTech.withBonus(20))
			.withItemEquipped(Clothing.mechanicusRobes)
			.withItemEquipped(MeleeWeapon.staff)
			.withItemInInventory(Tool.combiTool)
			.withItemInInventory(Tool.dataSlate)
			.withItemInInventory(MiscItem.glowGlobe)
			.withItemInInventory(Tool.lascutter)
			.withItemInInventory(MiscItem.gelt);
			
	public static final NPC omniprophet = new NPC("Omniprophet",
	        "40,40,30,40,30,40,35,30,30")
			.withSpecialRule(Talent.experienced.withParameter("Tech"))
			.withSpecialRule(Talent.language.withParameter("Binary + Low Gothic"))
			.withSpecialRule(Talent.operate_int.withParameter("1 Vehicle Type"))
			.withSpecialRule(Talent.trade.withParameter("Armourer/Mason/Shipwright/Technomat/Wright"))
			.withSpecialRule(Bionic.augurArray)
			.withSpecialRule(Bionic.bionicEverything)
			.withSpecialRule(Bionic.ferricLure)
			.withSpecialRule(Bionic.interfacePort)
			.withSpecialRule(Bionic.internalReservoir)
			.withSpecialRule(Bionic.luminenCapacitor)
			.withSpecialRule(Bionic.maglevCoils)
			.withSpecialRule(Bionic.mechanicusImplants)
			.withSpecialRule(Bionic.mechadendrite_ballistic)
			.withSpecialRule(Bionic.mechadendrite_manipulator)
			.withSpecialRule(Bionic.mechadendrite_optical)
			.withSpecialRule(Bionic.mechadendrite_utility)
			.withSpecialRule(Bionic.mindImpulseUnit)
			.withSkill(Skill.craft.withBonus(20))
			.withSkill(Skill.hack.withBonus(20))
			.withSkill(Skill.inquire.withBonus(10))
			.withSkill(Skill.inspect.withBonus(20))
			.withSkill(Skill.interrogate.withBonus(10))
			.withSkill(Skill.navigate.withBonus(20))
			.withSkill(Skill.referenceLore.withBonus(10))
			.withSkill(Skill.repair.withBonus(30))
			.withSkill(Skill.search.withBonus(20))
			.withSkill(Skill.useTech.withBonus(30))
			.withItemEquipped(Clothing.mechanicusRobes)
			.withItemEquipped(Armour.meshArmour)
			.withItemEquipped(MeleeWeapon.staff)
			.withItemInInventory(MeleeWeapon.chainsword_mastercrafted)
			.withItemInInventory(RangedWeapon.plasmaPistol)
			.withItemInInventory(Ammo.plasmaPistol_canister)
			.withItemInInventory(Tool.combiTool)
			.withItemInInventory(MiscItem.lampPack)
			.withItemInInventory(Tool.lascutter)
			.withItemInInventory(MiscItem.gelt);
			
	public static final NPC magos = new NPC("Magos",
	        "30,30,40,40,40,50,65,30,30")
			.withInsanity(20)
			.withSpecialRule(Talent.deepestSecrets.withParameter("Archeotech + The Warp"))
			.withSpecialRule(Talent.educated.withParameter("Astronomy + Chymistry + Cryptology + Numerology"))
			.withSpecialRule(Talent.experienced.withParameter("Tech"))
			.withSpecialRule(Talent.language.withParameter("Binary + Low Gothic"))
			.withSpecialRule(Talent.operate_int.withParameter("1 Vehicle Type"))
			.withSpecialRule(Talent.trade.withParameter("Armourer/Mason/Shipwright/Technomat/Wright"))
			.withSpecialRule(Bionic.augurArray_goodQuality)
			.withSpecialRule(Bionic.bionicEverything_goodQuality)
			.withSpecialRule(Bionic.cogitatorImplant)
			.withSpecialRule(Bionic.ferricLure)
			.withSpecialRule(Bionic.interfacePort)
			.withSpecialRule(Bionic.internalReservoir)
			.withSpecialRule(Bionic.luminenCapacitor)
			.withSpecialRule(Bionic.mechanicusImplants)
			.withSpecialRule(Bionic.mechadendrite_manipulator)
			.withSpecialRule(Bionic.mechadendrite_manipulator)
			.withSpecialRule(Bionic.mechadendrite_optical)
			.withSpecialRule(Bionic.mechadendrite_utility)
			.withSpecialRule(Bionic.mindImpulseUnit_goodQuality)
			.withSkill(Skill.craft.withBonus(20))
			.withSkill(Skill.hack.withBonus(20))
			.withSkill(Skill.inquire.withBonus(20))
			.withSkill(Skill.inspect.withBonus(20))
			.withSkill(Skill.interrogate.withBonus(20))
			.withSkill(Skill.referenceLore.withBonus(30))
			.withSkill(Skill.repair.withBonus(20))
			.withSkill(Skill.useTech.withBonus(20))
			.withItemEquipped(Clothing.mechanicusRobes)
			.withItemEquipped(MeleeWeapon.staff)
			.withItemInInventory(Tool.combiTool)
			.withItemInInventory(Tool.dataSlate)
			.withItemInInventory(MiscItem.glowGlobe)
			.withItemInInventory(Tool.lascutter)
			.withItemInInventory(MiscItem.gelt);
			
	public static final NPC magosErrant = new NPC("Magos Errant",
	        "45,45,50,45,45,40,70,40,30")
			.withSpecialRule(Talent.experienced.withParameter("Tech"))
			.withSpecialRule(Talent.ferricSummons)
			.withSpecialRule(Talent.language.withParameter("Binary + Low Gothic"))
			.withSpecialRule(Talent.maglevTranscendence)
			.withSpecialRule(Talent.operate_int.withParameter("1 Vehicle Type"))
			.withSpecialRule(Talent.trade.withParameter("Armourer/Mason/Shipwright/Technomat/Wright"))
			.withSpecialRule(Bionic.augurArray)
			.withSpecialRule(Bionic.bionicEverything_goodQuality)
			.withSpecialRule(Bionic.ferricLure)
			.withSpecialRule(Bionic.interfacePort)
			.withSpecialRule(Bionic.internalReservoir)
			.withSpecialRule(Bionic.luminenCapacitor)
			.withSpecialRule(Bionic.maglevCoils)
			.withSpecialRule(Bionic.mechanicusImplants)
			.withSpecialRule(Bionic.mechadendrite_ballistic)
			.withSpecialRule(Bionic.mechadendrite_manipulator)
			.withSpecialRule(Bionic.mechadendrite_optical)
			.withSpecialRule(Bionic.mechadendrite_utility)
			.withSpecialRule(Bionic.mindImpulseUnit_goodQuality)
			.withSkill(Skill.craft.withBonus(20))
			.withSkill(Skill.hack.withBonus(20))
			.withSkill(Skill.inquire.withBonus(10))
			.withSkill(Skill.inspect.withBonus(20))
			.withSkill(Skill.interrogate.withBonus(10))
			.withSkill(Skill.navigate.withBonus(20))
			.withSkill(Skill.referenceLore.withBonus(10))
			.withSkill(Skill.repair.withBonus(30))
			.withSkill(Skill.search.withBonus(20))
			.withSkill(Skill.useTech.withBonus(30))
			.withItemEquipped(Clothing.mechanicusRobes)
			.withItemEquipped(Armour.meshArmour_coweled)
			.withItemEquipped(MeleeWeapon.staff)
			.withItemInInventory(MeleeWeapon.chainsword_mastercrafted)
			.withItemInInventory(RangedWeapon.plasmaPistol)
			.withItemInInventory(Ammo.plasmaPistol_canister)
			.withItemInInventory(Tool.combiTool)
			.withItemInInventory(MiscItem.lampPack)
			.withItemInInventory(Tool.lascutter)
			.withItemInInventory(MiscItem.gelt);

	// Misc Characters //
	public static final NPC servoSkull = new NPC("Servo-Skull",
	        "10,10,05,05,10,05,20,00,00")
			.withSpecialRule(Trait.size_2)
			.withSpecialRule(Trait.flight.withParameter("3"))
			.withSpecialRule(Trait.machine)
			.withSpecialRule(Trait.programmedBehaviour)
			.withItemInInventory(Ammo.powerPack_small);
	public static final NPC servoSkull_illumination = new NPC("Servo-Skull (Illumination)",
	        "10,10,05,05,10,05,20,00,00")
			.withSpecialRule(Trait.size_2)
			.withSpecialRule(Trait.machine)
			.withSpecialRule(Trait.programmedBehaviour)
			.withSpecialRule(Trait.flight.withParameter("3"))
			.withItemInInventory(MiscItem.glowGlobe)
			.withItemInInventory(Ammo.powerPack_small);
	public static final NPC servoSkull_laudHailer = new NPC("Servo-Skull (Laud Hailer)",
	        "10,10,05,05,10,05,20,00,00")
			.withSpecialRule(Trait.size_2)
			.withSpecialRule(Trait.machine)
			.withSpecialRule(Trait.programmedBehaviour)
			.withSpecialRule(Trait.flight.withParameter("3"))
			.withItemInInventory(MiscItem.handVox)
			.withItemInInventory(MiscItem.laudHailer)
			.withItemInInventory(Ammo.powerPack_small);
	public static final NPC servoSkull_combat = new NPC("Servo-Skull (Combat)",
	        "10,20,05,05,10,05,20,00,00")
			.withSpecialRule(Trait.size_2)
			.withSpecialRule(Trait.machine)
			.withSpecialRule(Trait.programmedBehaviour)
			.withSpecialRule(Trait.flight.withParameter("3"))
			.withItemEquipped(RangedWeapon.laspistol)
			.withItemInInventory(Ammo.laspistol_powerPack)
			.withItemInInventory(Ammo.powerPack_small);
	
	NPCGroup_AdeptusMechanicus() {
		super("Adeptus Mechanicus");
		rankedCharacterList.add(technographer);
		rankedCharacterList.add(mechWright);
		rankedCharacterList.add(electroPriest);
		rankedCharacterList.add(engineSeer);
		rankedCharacterList.add(techPriest);
		rankedCharacterList.add(techPriest_chirurgeon);
		rankedCharacterList.add(techPriest_militant);
		rankedCharacterList.add(technomancer);
		rankedCharacterList.add(mechDeacon);
		rankedCharacterList.add(cyberSeer);
		rankedCharacterList.add(omniprophet);
		rankedCharacterList.add(magos);
		rankedCharacterList.add(magosErrant);
		miscCharacterList.add(servoSkull);
		miscCharacterList.add(servoSkull_illumination);
		miscCharacterList.add(servoSkull_laudHailer);
		miscCharacterList.add(servoSkull_combat);
		// TODO - augur servo-skull
		// TODO - medicae servo-skull
		// TODO - utility servo-skull
		// TODO - pict/watcher servo-skull
		// TODO - combat servo-skull
	}
}